/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "servidor.h"

bool_t
xdr_argumento (XDR *xdrs, argumento *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->frase, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
