/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "servidor.h"


void
punto2server_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	char  cant_carac_e_1_arg;
	int  *result_2;
	char  cant_carac_se_1_arg;
	int  *result_3;
	char  cant_palabras_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, Punto2Server, VERSION_PROGRAMA, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = cant_carac_e_1(&cant_carac_e_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = cant_carac_se_1(&cant_carac_se_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = cant_palabras_1(&cant_palabras_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	punto2server_1 (host);
exit (0);
}
