/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERVIDOR_H_RPCGEN
#define _SERVIDOR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define Punto2Server 0x20000001
#define VERSION_PROGRAMA 1

#if defined(__STDC__) || defined(__cplusplus)
#define cant_carac_e 1
extern  int * cant_carac_e_1(char *, CLIENT *);
extern  int * cant_carac_e_1_svc(char *, struct svc_req *);
#define cant_carac_se 2
extern  int * cant_carac_se_1(char *, CLIENT *);
extern  int * cant_carac_se_1_svc(char *, struct svc_req *);
#define cant_palabras 3
extern  int * cant_palabras_1(char *, CLIENT *);
extern  int * cant_palabras_1_svc(char *, struct svc_req *);
extern int punto2server_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define cant_carac_e 1
extern  int * cant_carac_e_1();
extern  int * cant_carac_e_1_svc();
#define cant_carac_se 2
extern  int * cant_carac_se_1();
extern  int * cant_carac_se_1_svc();
#define cant_palabras 3
extern  int * cant_palabras_1();
extern  int * cant_palabras_1_svc();
extern int punto2server_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SERVIDOR_H_RPCGEN */
