/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "servidor.h"
#include <string.h>

int *cant_carac_e_1_svc(argumento *palabras, struct svc_req *rqstp)
{
	static int result=0;

	char *frase;
	frase = palabras->frase;
	result = strlen(frase);
	return &result;
}
int *cant_carac_se_1_svc(argumento *palabras, struct svc_req *rqstp)
{
	static int result=0;
	int aux=0;
	char *frase;
	frase = palabras->frase;
	while (*frase)
	{
		if (*frase == ' ' || *frase == '\n' || *frase == '\t')
		{
			//nada
		}
		else
		{
			aux++;
		}
		++frase;
	}
	result=aux;
	return &result;
}

int *cant_palabras_1_svc(argumento *palabras, struct svc_req *rqstp)
{
	static int result=0;
	int aux=0;
	char *frase;
	frase = palabras->frase;

	int siguiente = 0;

	while (*frase)
	{
		if (*frase == ' ' || *frase == '\n' || *frase == '\t')
		{
			siguiente = 0; // si encuentra una de esas expresiones es porque tiene que pasar a la siguiente palabra
		}
		else if (siguiente == 0)
		{ // se setea "siguiente" en 1 cuando termina una palabra
			siguiente = 1;
			aux++;
		}
		++frase;
	}
	result=aux;
	return &result;
}
