/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Operandos {
	int operando1;
	int operando2;
};
typedef struct Operandos Operandos;

#define CALCULADORA 0x20000001
#define CALCULADORAVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMAR 1
extern  int * sumar_1(Operandos *, CLIENT *);
extern  int * sumar_1_svc(Operandos *, struct svc_req *);
#define RESTAR 2
extern  int * restar_1(Operandos *, CLIENT *);
extern  int * restar_1_svc(Operandos *, struct svc_req *);
#define MULTIPLICAR 3
extern  int * multiplicar_1(Operandos *, CLIENT *);
extern  int * multiplicar_1_svc(Operandos *, struct svc_req *);
#define DIVIDIR 4
extern  double * dividir_1(Operandos *, CLIENT *);
extern  double * dividir_1_svc(Operandos *, struct svc_req *);
extern int calculadora_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMAR 1
extern  int * sumar_1();
extern  int * sumar_1_svc();
#define RESTAR 2
extern  int * restar_1();
extern  int * restar_1_svc();
#define MULTIPLICAR 3
extern  int * multiplicar_1();
extern  int * multiplicar_1_svc();
#define DIVIDIR 4
extern  double * dividir_1();
extern  double * dividir_1_svc();
extern int calculadora_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Operandos (XDR *, Operandos*);

#else /* K&R C */
extern bool_t xdr_Operandos ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
