/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "my_FS.h"


void
filesystem_1(char *host)
{
	CLIENT *clnt;
	str_t  *result_1;
	argumento  getfile_1_arg;
	int  *result_2;
	char *wait_1_arg;
	int  *result_3;
	char *signal_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, FILESYSTEM, FILESYSTEMVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = getfile_1(&getfile_1_arg, clnt);
	if (result_1 == (str_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = wait_1((void*)&wait_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = signal_1((void*)&signal_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	filesystem_1 (host);
exit (0);
}
